language: node_js
node_js:
- '10'
env:
  global:
  - CXX=g++-4.8
  - APPLITOOLS_BATCH_ID=`echo ${TRAVIS_PULL_REQUEST_SHA:=$TRAVIS_JOB_ID}`
  - secure: Uhe4xdh0EMZ/joDwKriZgq1WL219w7F5Wa1rJKROfAjMtSkCVCPuXziF6mbqFMz/fuV4JiFW++QvJ10OM5AK45cZHRUnJeEtTOwJE78s0H7FXWsAGzxvyTQvT5/zLQgAlfTva7cQ0Rm4WubB4EWdxVOat78yuE0ooGCvME7i1h8g7YeE8L1xkv68nMdCDSP1bVwbS21MA0Bss4Hj6UBqJXSyGaAcWxzf3TMSVYV7bVAP7nM8JmaRYu2w7Yk8A4V0foFpkA0ztrgI1pYggaY0GruFt3B9mbtp6UT98Jm5uwww/Jh69F9XOdgf/n+9ubVzXfJJbvZSJMG+mMA5euKxxlDwtEoKN6QfGzIqzeIgZEKmaUFrbAQ8+E/4L1x8BQ0NxrKaa9mrD+mqn6H0Z/ZamAH61QRSqkgFkddAHyf09pMjr1I4q/6yBq7EAkLRdzwUGo3NHmfNCHhLv9tGO3AOt8txXA3PvESGpJ6GbDcOjad/q+7YbjwGGj3+HXFkKNYMOl3xQMJ1xtCPe/6ApMwCs525h5jdsXoui2nRUJh1zrelFjSsVdEa43jNL8w4glGkeaaHbTxXll8za1M3BEwPUCfVVMB15pYlchvEWxIXBIjcFzvGufJRTmgmdBDl/VLCzYjq0orDO4AspwlZacLddlEfa5Bc73XR2szUPczfSDA=
  matrix:
  - TEST_SUITE='test:travis'
  - TEST_SUITE='test:visual set1'
  - TEST_SUITE='test:visual set2'
  - TEST_SUITE='test:visual set3'
  - TEST_SUITE='test:visual set4'
  - TEST_SUITE='test:applitools'
sudo: required
dist: trusty
group: edge
notifications:
  email:
  - wilkenj@vmware.com
  - mhippely@vmware.com
  slack:
    secure: YiAUJjD3zKQvRw1TrlmC/3vhm2J9gZBS74pTssohEStqxAq5KCW97xF5ZgeB9xr2/Vx1//40Jncl4PkvvSXGMJ6RDS8yh8fs+LzCytZzbo8WWL60mEX4Ezq7PwyBHshInMAilXNJvplWwSynR2YJwAD9BKIDtIv2uFNBzdr1OPNu3F6Ta3OVUMIaUUDYtmFAPUu0q7VCX6VcTiy8lvkpN5acTwvy+LcbVGbCK2Uzw8xXHV3tRY+PyhBynM1VZiGMPwVTUZV1S0GnZrSdwzGSHMuBHtJ1wwEy9nk/2FtBFfxa8LNE0s7JaqJLvcTfs9pHdz5BBuQvk2lLl0nf6QfK9z5HZJ45U8ezumIaAWRbATyQk49R/d2QBeIN89GYNq1bQdryIKoiMksH4wbBzuAJLjeEJmzTel8isUbhS1GU9M5Fch5/AL7vjdLHmul58z0rTccy4wA9kINU9S21Fxsx29Z4g02VegECfcAlKaIY6WjRCISKlg7ENQWEZRGV7bD/DnNsdoXhXPhXADi996CJPQx45bnbtzCLK+Aa3wlq+CjBeKyhecKoLC36WYAlAKZ0ZbuYXfMlDUtVMAY9oStKnDjoCGDBb3O4LH66CFRgW+CzjV8UgtggAgpCi4m5O4tl/o95WkF/YEul07qaHAftJCoEVMcXxb37gTkkqJdW2C0=
services:
- docker
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - google-chrome
    packages:
    - g++-4.8
    - google-chrome-stable
cache:
  apt: true
  directories:
  - node_modules
script:
- node scripts/travis
#jobs:
#  include:
#  - stage: publish
#    if: "(NOT type IN (api, cron, pull_request)) AND branch = master AND repo = vmware/clarity"
#    before_script:
#    - npm run build
#    script:
#    - bash ./scripts/publish-build.sh
